fix a little issue about  MASAttachKeys(...)
if we have many view in a method, so we want to use MASAttachKeys(...)  many times.
for example:

- (void)initSubviews
{
    UIView *view1 = [UIView new];
    UIView *view2 = [UIView new];
    UIView *view3 = [UIView new];
    MASAttachKeys(view1,view2,view3);

    UIView *view4 = [UIView new];
    UIView *view5 = [UIView new];
    UIView *view6 = [UIView new];
    MASAttachKeys(view4,view5,view6);
}
than there is a error: Redefinition of 'keyPairs'
I fix it by add a "{ }"